module r_case;

  initial begin
    // Display messages explaining the behavior of randcase
    $display("Random data will be generated by simulator");
    $display("data from 0 to 3 then it will display randcase output");

    // Loop to generate random outputs using randcase
    for (int i = 0; i < 6; i++) begin
      randcase
        0: $display("\t \n output of randcase 0"); // Case 0 with weight 0
        1: $display("\t \n output of randcase 1"); // Case 1 with weight 1
        2: $display("\t \n output of randcase 2"); // Case 2 with weight 2
        3: $display("\t \n output of randcase 3"); // Case 3 with weight 3
      endcase
    end
  end

endmodule
