
simulate:                                                                                           
	vcs -V -R -full64 -sverilog +v2k -debug_access +all sequence.sv -l sequence.log 


waveform:                                                                                           
	nWave waveform.vcd                                                                                



all:                                                                                                
	vcs -V -R -full64 -sverilog +v2k -debug_access+all sequence.sv -l sequence.log      
	nWave waveform.vcd    
